In [2]:
!rm Chinook.zip

rm: cannot remove 'Chinook.zip': No such file or directory

In [3]:
!rm -f *.csv

In [4]:
!wget https://github.com/CS639-Data-Management-for-Data-Science/s25/raw/main/p1/Chinook.zip

--2025-02-16 19:31:37--  https://github.com/CS639-Data-Management-for-Data-Science/s25/raw/main/p1/Chinook.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/CS639-Data-Management-for-Data-Science/s25/main/p1/Chinook.zip [following]
--2025-02-16 19:31:38--  https://raw.githubusercontent.com/CS639-Data-Management-for-Data-Science/s25/main/p1/Chinook.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
200 OKequest sent, awaiting response...
Length: 146381 (143K) [application/zip]
Saving to: ‘Chinook.zip’

Chinook.zip         100%[===================>] 142.95K  --.-KB/s    in 0.02s

2025-02-16 19:31:38 (6.51 MB/s) - ‘Chinook.zip’ saved [146381/146381]

In [5]:
!unzip -o Chinook.zip

Archive:  Chinook.zip
  inflating: Album.csv
  inflating: Artist.csv
  inflating: Customer.csv
  inflating: Employee.csv
  inflating: Genre.csv
  inflating: Invoice.csv
  inflating: InvoiceLine.csv
  inflating: MediaType.csv
  inflating: Playlist.csv
  inflating: PlaylistTrack.csv
  inflating: Track.csv

In [7]:
from sqlalchemy import create_engine, text
import pandas as pd
import os

In [9]:
engine = create_engine("mysql+mysqlconnector://root:123456@127.0.0.1:3306/Chinook")
conn = engine.connect()

In [14]:
files = os.listdir()
csv_files = [f for f in files if ".csv" in f]
table_names = [f.replace(".csv", "") for f in csv_files]
table_names = [f.replace(".", "_") for f in table_names]

In [15]:
for idx, csv_file in enumerate(csv_files):
    df = pd.read_csv(csv_file, sep=",", na_values='\\N')
    df.to_sql(table_names[idx], conn, index=False, if_exists="replace")
    print(f"Populated {table_names[idx]}")

Populated Employee
Populated Album
Populated Genre
Populated Track
Populated InvoiceLine
Populated Playlist
Populated Customer
Populated Artist
Populated MediaType
Populated PlaylistTrack
Populated Invoice

In [16]:
!python3 autograder.py

Archive:  answers.zip
   creating: answers/answers/
   creating: answers/answers/.ipynb_checkpoints/
   creating: answers/answers/pkls/
  inflating: answers/answers/pkls/p24.pkl
  inflating: answers/answers/pkls/p31.pkl
  inflating: answers/answers/pkls/p5.pkl
  inflating: answers/answers/pkls/p2.pkl
  inflating: answers/answers/pkls/p29.pkl
  inflating: answers/answers/pkls/p4.pkl
  inflating: answers/answers/pkls/p30.pkl
  inflating: answers/answers/pkls/p8.pkl
  inflating: answers/answers/pkls/p3.pkl
  inflating: answers/answers/pkls/p6.pkl
  inflating: answers/answers/pkls/p22.pkl
  inflating: answers/answers/pkls/p23-s2.pkl
  inflating: answers/answers/pkls/p13.pkl
  inflating: answers/answers/pkls/p23.pkl
  inflating: answers/answers/pkls/p9.pkl
  inflating: answers/answers/pkls/p34.pkl
  inflating: answers/answers/pkls/p20.pkl
  inflating: answers/answers/pkls/p12.pkl
  inflating: answers/answers/pkls/p1.pkl
  inflating: answers/answers/pkls/p32.pkl
  inflating: answers/answers/pkls/p33.pkl
  inflating: answers/answers/pkls/p27.pkl
  inflating: answers/answers/pkls/p7.pkl
  inflating: answers/answers/pkls/p11.pkl
  inflating: answers/answers/pkls/p18.pkl
  inflating: answers/answers/pkls/p26.pkl
  inflating: answers/answers/pkls/p25.pkl
  inflating: answers/answers/pkls/p15.pkl
  inflating: answers/answers/pkls/p14.pkl
  inflating: answers/answers/pkls/p35.pkl
  inflating: answers/answers/pkls/p21.pkl
  inflating: answers/answers/pkls/p28.pkl
  inflating: answers/answers/pkls/p17.pkl
  inflating: answers/answers/pkls/p10.pkl
  inflating: answers/answers/pkls/p19.pkl
  inflating: answers/answers/pkls/p16.pkl
-----------------------------
Total Score: 2.5/90.0
-----------------------------
Run `cat test_output.txt` for individual question-wise results :)

In [31]:
#q1
query = """
SELECT * FROM Artist WHERE Name = 'Queen';
"""
q1_df = pd.read_sql(query, engine)
q1_df.to_pickle("q1.pkl")
q1_df

   ArtistId   Name
0        51  Queen

In [32]:
#q2
query = """
SELECT * FROM Album
WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen');
"""
q2_df = pd.read_sql(query, engine)
q2_df.to_pickle("q2.pkl")
q2_df

   AlbumId              Title  ArtistId
0       36   Greatest Hits II        51
1      185    Greatest Hits I        51
2      186  News Of The World        51

In [41]:
#q3
query = """
SELECT * FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
);
"""
q3_df = pd.read_sql(query, engine)
q3_df.to_pickle("q3.pkl")
q3_df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,419,A Kind Of Magic,36,1,1,Roger Taylor,262608,8689618,0.99
1,420,Under Pressure,36,1,1,Queen & David Bowie,236617,7739042,0.99
2,421,Radio GA GA,36,1,1,Roger Taylor,343745,11358573,0.99
3,422,I Want It All,36,1,1,Queen,241684,7876564,0.99
4,423,I Want To Break Free,36,1,1,John Deacon,259108,8552861,0.99
5,424,Innuendo,36,1,1,Queen,387761,12664591,0.99
6,425,It's A Hard Life,36,1,1,Freddie Mercury,249417,8112242,0.99
7,426,Breakthru,36,1,1,Queen,249234,8150479,0.99
8,427,Who Wants To Live Forever,36,1,1,Brian May,297691,9577577,0.99
9,428,Headlong,36,1,1,Queen,273057,8921404,0.99
10,429,The Miracle,36,1,1,Queen,294974,9671923,0.99
11,430,I'm Going Slightly Mad,36,1,1,Queen,248032,8192339,0.99
12,431,The Invisible Man,36,1,1,Queen,238994,7920353,0.99
13,432,Hammer To Fall,36,1,1,Brian May,220316,7255404,0.99
14,433,Friends Will Be Friends,36,1,1,Freddie Mercury & John Deacon,248920,8114582,0.99
15,434,The Show Must Go On,36,1,1,Queen,263784,8526760,0.99
16,435,One Vision,36,1,1,Queen,242599,7936928,0.99
17,2254,Bohemian Rhapsody,185,1,1,"Mercury, Freddie",358948,11619868,0.99
18,2255,Another One Bites The Dust,185,1,1,"Deacon, John",216946,7172355,0.99
19,2256,Killer Queen,185,1,1,"Mercury, Freddie",182099,5967749,0.99
20,2257,Fat Bottomed Girls,185,1,1,"May, Brian",204695,6630041,0.99
21,2258,Bicycle Race,185,1,1,"Mercury, Freddie",183823,6012409,0.99
22,2259,You're My Best Friend,185,1,1,"Deacon, John",172225,5602173,0.99
23,2260,Don't Stop Me Now,185,1,1,"Mercury, Freddie",211826,6896666,0.99
24,2261,Save Me,185,1,1,"May, Brian",228832,7444624,0.99
25,2262,Crazy Little Thing Called Love,185,1,1,"Mercury, Freddie",164231,5435501,0.99
26,2263,Somebody To Love,185,1,1,"Mercury, Freddie",297351,9650520,0.99
27,2264,Now I'm Here,185,1,1,"May, Brian",255346,8328312,0.99
28,2265,Good Old-Fashioned Lover Boy,185,1,1,"Mercury, Freddie",175960,5747506,0.99
29,2266,Play The Game,185,1,1,"Mercury, Freddie",213368,6915832,0.99
30,2267,Flash,185,1,1,"May, Brian",168489,5464986,0.99
31,2268,Seven Seas Of Rhye,185,1,1,"Mercury, Freddie",170553,5539957,0.99
32,2269,We Will Rock You,185,1,1,"Deacon, John/May, Brian",122880,4026955,0.99
33,2270,We Are The Champions,185,1,1,"Mercury, Freddie",180950,5880231,0.99
34,2271,We Will Rock You,186,1,1,May,122671,4026815,0.99
35,2272,We Are The Champions,186,1,1,Mercury,182883,5939794,0.99
36,2273,Sheer Heart Attack,186,1,1,Taylor,207386,6642685,0.99
37,2274,"All Dead, All Dead",186,1,1,May,190119,6144878,0.99
38,2275,Spread Your Wings,186,1,1,Deacon,275356,8936992,0.99
39,2276,Fight From The Inside,186,1,1,Taylor,184737,6078001,0.99
40,2277,"Get Down, Make Love",186,1,1,Mercury,231235,7509333,0.99
41,2278,Sleep On The Sidewalk,186,1,1,May,187428,6099840,0.99
42,2279,Who Needs You,186,1,1,Deacon,186958,6292969,0.99
43,2280,It's Late,186,1,1,May,386194,12519388,0.99
44,2281,My Melancholy Blues,186,1,1,Mercury,206471,6691838,0.99

In [48]:
#q4
query = """
SELECT COUNT(*) AS TotalQueenTracks FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
) AND Composer LIKE '%Queen%';
"""
q4_df = pd.read_sql(query, engine)
q4_df.to_pickle("q4.pkl")
q4_df

   TotalQueenTracks
0                10

In [115]:
#q5
query = """
SELECT DISTINCT Composer FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
) AND Composer IS NOT NULL;
"""
q5_df = pd.read_sql(query, engine)
q5_df.to_pickle("q5.pkl")
q5_df

                         Composer
0                    Roger Taylor
1             Queen & David Bowie
2                           Queen
3                     John Deacon
4                 Freddie Mercury
5                       Brian May
6   Freddie Mercury & John Deacon
7                Mercury, Freddie
8                    Deacon, John
9                      May, Brian
10        Deacon, John/May, Brian
11                            May
12                        Mercury
13                         Taylor
14                         Deacon

In [116]:
#q6
query = """
SELECT TrackId, Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice
FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
)
ORDER BY Milliseconds DESC
LIMIT 5;
"""
q6_df = pd.read_sql(query, engine)
q6_df.to_pickle("q6.pkl")
q6_df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,424,Innuendo,36,1,1,Queen,387761,12664591,0.99
1,2280,It's Late,186,1,1,May,386194,12519388,0.99
2,2254,Bohemian Rhapsody,185,1,1,"Mercury, Freddie",358948,11619868,0.99
3,421,Radio GA GA,36,1,1,Roger Taylor,343745,11358573,0.99
4,427,Who Wants To Live Forever,36,1,1,Brian May,297691,9577577,0.99

In [117]:
#q7
query = """
SELECT TrackId, Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice
FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
)
AND Bytes < 6 * 1000000;
"""
q7_df = pd.read_sql(query, engine)
q7_df.to_pickle("q7.pkl")
q7_df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2256,Killer Queen,185,1,1,"Mercury, Freddie",182099,5967749,0.99
1,2259,You're My Best Friend,185,1,1,"Deacon, John",172225,5602173,0.99
2,2262,Crazy Little Thing Called Love,185,1,1,"Mercury, Freddie",164231,5435501,0.99
3,2265,Good Old-Fashioned Lover Boy,185,1,1,"Mercury, Freddie",175960,5747506,0.99
4,2267,Flash,185,1,1,"May, Brian",168489,5464986,0.99
5,2268,Seven Seas Of Rhye,185,1,1,"Mercury, Freddie",170553,5539957,0.99
6,2269,We Will Rock You,185,1,1,"Deacon, John/May, Brian",122880,4026955,0.99
7,2270,We Are The Champions,185,1,1,"Mercury, Freddie",180950,5880231,0.99
8,2271,We Will Rock You,186,1,1,May,122671,4026815,0.99
9,2272,We Are The Champions,186,1,1,Mercury,182883,5939794,0.99

In [225]:
#q8
query = """
SELECT Name AS Name,  -- Rename TrackName back to Name
       ROUND(Milliseconds / 60000, 4) AS DurationMinutes,
       ROUND(Bytes / 1000000, 4) AS FileSize  -- Increase precision to 4 decimal places
FROM Track
WHERE AlbumId IN (
    SELECT AlbumId FROM Album
    WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'Queen')
);
"""
q8_df = pd.read_sql(query, engine)
q8_df.to_pickle("q8.pkl")
q8_df

                              Name  DurationMinutes  FileSize
0                  A Kind Of Magic           4.3768    8.6896
1                   Under Pressure           3.9436    7.7390
2                      Radio GA GA           5.7291   11.3586
3                    I Want It All           4.0281    7.8766
4             I Want To Break Free           4.3185    8.5529
5                         Innuendo           6.4627   12.6646
6                 It's A Hard Life           4.1570    8.1122
7                        Breakthru           4.1539    8.1505
8        Who Wants To Live Forever           4.9615    9.5776
9                         Headlong           4.5510    8.9214
10                     The Miracle           4.9162    9.6719
11          I'm Going Slightly Mad           4.1339    8.1923
12               The Invisible Man           3.9832    7.9204
13                  Hammer To Fall           3.6719    7.2554
14         Friends Will Be Friends           4.1487    8.1146
15             The Show Must Go On           4.3964    8.5268
16                      One Vision           4.0433    7.9369
17               Bohemian Rhapsody           5.9825   11.6199
18      Another One Bites The Dust           3.6158    7.1724
19                    Killer Queen           3.0350    5.9677
20              Fat Bottomed Girls           3.4116    6.6300
21                    Bicycle Race           3.0637    6.0124
22           You're My Best Friend           2.8704    5.6022
23               Don't Stop Me Now           3.5304    6.8967
24                         Save Me           3.8139    7.4446
25  Crazy Little Thing Called Love           2.7372    5.4355
26                Somebody To Love           4.9559    9.6505
27                    Now I'm Here           4.2558    8.3283
28    Good Old-Fashioned Lover Boy           2.9327    5.7475
29                   Play The Game           3.5561    6.9158
30                           Flash           2.8082    5.4650
31              Seven Seas Of Rhye           2.8426    5.5400
32                We Will Rock You           2.0480    4.0270
33            We Are The Champions           3.0158    5.8802
34                We Will Rock You           2.0445    4.0268
35            We Are The Champions           3.0481    5.9398
36              Sheer Heart Attack           3.4564    6.6427
37              All Dead, All Dead           3.1687    6.1449
38               Spread Your Wings           4.5893    8.9370
39           Fight From The Inside           3.0790    6.0780
40             Get Down, Make Love           3.8539    7.5093
41           Sleep On The Sidewalk           3.1238    6.0998
42                   Who Needs You           3.1160    6.2930
43                       It's Late           6.4366   12.5194
44             My Melancholy Blues           3.4412    6.6918

In [226]:
#q9
query = """
SELECT CustomerId, FirstName, LastName, State
FROM Customer
WHERE Country = 'USA'
ORDER BY State ASC;
"""
q9_df = pd.read_sql(query, engine)
q9_df.to_pickle("q9.pkl")
q9_df

    CustomerId FirstName    LastName State
0           27   Patrick        Gray    AZ
1           16     Frank      Harris    CA
2           19       Tim       Goyer    CA
3           20       Dan      Miller    CA
4           22   Heather     Leacock    FL
5           24     Frank     Ralston    IL
6           23      John      Gordon    MA
7           21     Kathy       Chase    NV
8           18  Michelle      Brooks    NY
9           26   Richard  Cunningham    TX
10          28     Julia     Barnett    UT
11          17      Jack       Smith    WA
12          25    Victor     Stevens    WI

In [227]:
#q10
query = """
SELECT *
FROM Invoice
WHERE Total > 20;
"""
q10_df = pd.read_sql(query, engine)
q10_df.to_pickle("q10.pkl")
q10_df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,96,45,2022-02-18,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
1,194,46,2023-04-28,3 Chatham Street,Dublin,Dublin,Ireland,None,21.86
2,299,26,2024-08-05,2211 W Berry Street,Fort Worth,TX,USA,76110,23.86
3,404,6,2025-11-13,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86

In [228]:
#q11
query = """
SELECT *
FROM Invoice
WHERE YEAR(InvoiceDate) = 2021;
"""
q11_df = pd.read_sql(query, engine)
q11_df.to_pickle("q11.pkl")
q11_df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2021-01-02,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2021-01-03,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2021-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
78,79,9,2021-12-09,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,3.96
79,80,13,2021-12-10,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,5.94
80,81,19,2021-12-13,1 Infinite Loop,Cupertino,CA,USA,95014,8.91
81,82,28,2021-12-18,302 S 700 E,Salt Lake City,UT,USA,84102,13.86
82,83,42,2021-12-26,"9, Place Louis Barthou",Bordeaux,None,France,33000,0.99

In [229]:
#q12
query = """
SELECT SUM(Total) AS TotalSpent
FROM Invoice
WHERE CustomerId = (
    SELECT CustomerId FROM Customer
    WHERE FirstName = 'Eduardo' AND LastName = 'Martins'
);
"""
q12_df = pd.read_sql(query, engine)
q12_df.to_pickle("q12.pkl")
q12_df

   TotalSpent
0       37.62

In [230]:
#q13
query = """
SELECT *
FROM Customer
WHERE Country = 'USA' AND Company IS NULL;
"""
q13_df = pd.read_sql(query, engine)
q13_df.to_pickle("q13.pkl")
q13_df

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
1,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
2,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
3,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
4,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
5,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
6,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
7,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
8,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
9,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5

In [231]:
#q14
query = """
SELECT *
FROM Employee
WHERE Country = 'Canada';
"""
q14_df = pd.read_sql(query, engine)
q14_df.to_pickle("q14.pkl")
q14_df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01,2003-10-17,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29,2004-01-02,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09,2004-03-04,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [232]:
#q15
query = """
SELECT Customer.FirstName, Customer.LastName, Invoice.Total
FROM Customer
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
ORDER BY Customer.LastName ASC, Invoice.Total ASC;
"""
q15_df = pd.read_sql(query, engine)
q15_df.to_pickle("q15.pkl")
q15_df

    FirstName    LastName  Total
0     Roberto     Almeida   0.99
1     Roberto     Almeida   1.98
2     Roberto     Almeida   1.98
3     Roberto     Almeida   3.96
4     Roberto     Almeida   5.94
..        ...         ...    ...
407      Fynn  Zimmermann   1.98
408      Fynn  Zimmermann   3.96
409      Fynn  Zimmermann   5.94
410      Fynn  Zimmermann  13.86
411      Fynn  Zimmermann  14.91

[412 rows x 3 columns]

In [233]:
#q16
query = """
SELECT DISTINCT Customer.CustomerId, Customer.FirstName, Customer.LastName
FROM Customer
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
WHERE InvoiceLine.TrackId IN (
    SELECT Track.TrackId
    FROM Track
    JOIN Album ON Track.AlbumId = Album.AlbumId
    JOIN Artist ON Album.ArtistId = Artist.ArtistId
    WHERE Artist.Name = 'Queen'
)
ORDER BY Customer.CustomerId;
"""
q16_df = pd.read_sql(query, engine)
q16_df.to_pickle("q16.pkl")
q16_df

    CustomerId  FirstName    LastName
0            2     Leonie      Köhler
1           11  Alexandre       Rocha
2           24      Frank     Ralston
3           27    Patrick        Gray
4           29     Robert       Brown
5           30     Edward     Francis
6           33      Ellie    Sullivan
7           38     Niklas    Schröder
8           40  Dominique    Lefebvre
9           41       Marc      Dubois
10          44      Terhi  Hämäläinen
11          45   Ladislav      Kovács
12          47      Lucas     Mancini
13          49  Stanisław      Wójcik
14          50    Enrique       Muñoz

In [234]:
#q17
query = """
SELECT DISTINCT Invoice.InvoiceId, Invoice.InvoiceDate, Invoice.BillingCountry, Invoice.Total
FROM Invoice
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
WHERE InvoiceLine.TrackId IN (
    SELECT Track.TrackId
    FROM Track
    JOIN Album ON Track.AlbumId = Album.AlbumId
    JOIN Artist ON Album.ArtistId = Artist.ArtistId
    WHERE Artist.Name = 'Queen'
)
ORDER BY Invoice.InvoiceId;
"""
q17_df = pd.read_sql(query, engine)
q17_df.to_pickle("q17.pkl")
q17_df

    InvoiceId InvoiceDate BillingCountry  Total
0          12  2021-02-11        Germany  13.86
1          68  2021-10-17         Brazil  13.86
2         117  2022-05-22         France  13.86
3         173  2023-01-25          Spain  13.86
4         225  2023-09-20        Germany   1.98
5         226  2023-09-21         France   3.96
6         227  2023-09-22        Finland   5.94
7         278  2024-05-04         Canada  13.86
8         279  2024-05-12        Finland   0.99
9         280  2024-05-25        Hungary   1.98
10        281  2024-05-25          Italy   1.98
11        282  2024-05-26         Poland   3.96
12        332  2024-12-30            USA   5.94
13        386  2025-09-02            USA   1.98
14        387  2025-09-03         Canada   3.96
15        388  2025-09-04         Canada   5.94

In [235]:
#q18
query = """
SELECT Track.TrackId, Track.Name AS TrackName, Album.Title AS AlbumTitle, MediaType.Name AS MediaTypeName
FROM Track
JOIN Album ON Track.AlbumId = Album.AlbumId
JOIN Artist ON Album.ArtistId = Artist.ArtistId
JOIN MediaType ON Track.MediaTypeId = MediaType.MediaTypeId
WHERE Artist.Name = 'Queen'
ORDER BY Track.TrackId;
"""
q18_df = pd.read_sql(query, engine)
q18_df.to_pickle("q18.pkl")
q18_df

,TrackId,TrackName,AlbumTitle,MediaTypeName
0,419,A Kind Of Magic,Greatest Hits II,MPEG audio file
1,420,Under Pressure,Greatest Hits II,MPEG audio file
2,421,Radio GA GA,Greatest Hits II,MPEG audio file
3,422,I Want It All,Greatest Hits II,MPEG audio file
4,423,I Want To Break Free,Greatest Hits II,MPEG audio file
5,424,Innuendo,Greatest Hits II,MPEG audio file
6,425,It's A Hard Life,Greatest Hits II,MPEG audio file
7,426,Breakthru,Greatest Hits II,MPEG audio file
8,427,Who Wants To Live Forever,Greatest Hits II,MPEG audio file
9,428,Headlong,Greatest Hits II,MPEG audio file
10,429,The Miracle,Greatest Hits II,MPEG audio file
11,430,I'm Going Slightly Mad,Greatest Hits II,MPEG audio file
12,431,The Invisible Man,Greatest Hits II,MPEG audio file
13,432,Hammer To Fall,Greatest Hits II,MPEG audio file
14,433,Friends Will Be Friends,Greatest Hits II,MPEG audio file
15,434,The Show Must Go On,Greatest Hits II,MPEG audio file
16,435,One Vision,Greatest Hits II,MPEG audio file
17,2254,Bohemian Rhapsody,Greatest Hits I,MPEG audio file
18,2255,Another One Bites The Dust,Greatest Hits I,MPEG audio file
19,2256,Killer Queen,Greatest Hits I,MPEG audio file
20,2257,Fat Bottomed Girls,Greatest Hits I,MPEG audio file
21,2258,Bicycle Race,Greatest Hits I,MPEG audio file
22,2259,You're My Best Friend,Greatest Hits I,MPEG audio file
23,2260,Don't Stop Me Now,Greatest Hits I,MPEG audio file
24,2261,Save Me,Greatest Hits I,MPEG audio file
25,2262,Crazy Little Thing Called Love,Greatest Hits I,MPEG audio file
26,2263,Somebody To Love,Greatest Hits I,MPEG audio file
27,2264,Now I'm Here,Greatest Hits I,MPEG audio file
28,2265,Good Old-Fashioned Lover Boy,Greatest Hits I,MPEG audio file
29,2266,Play The Game,Greatest Hits I,MPEG audio file
30,2267,Flash,Greatest Hits I,MPEG audio file
31,2268,Seven Seas Of Rhye,Greatest Hits I,MPEG audio file
32,2269,We Will Rock You,Greatest Hits I,MPEG audio file
33,2270,We Are The Champions,Greatest Hits I,MPEG audio file
34,2271,We Will Rock You,News Of The World,MPEG audio file
35,2272,We Are The Champions,News Of The World,MPEG audio file
36,2273,Sheer Heart Attack,News Of The World,MPEG audio file
37,2274,"All Dead, All Dead",News Of The World,MPEG audio file
38,2275,Spread Your Wings,News Of The World,MPEG audio file
39,2276,Fight From The Inside,News Of The World,MPEG audio file
40,2277,"Get Down, Make Love",News Of The World,MPEG audio file
41,2278,Sleep On The Sidewalk,News Of The World,MPEG audio file
42,2279,Who Needs You,News Of The World,MPEG audio file
43,2280,It's Late,News Of The World,MPEG audio file
44,2281,My Melancholy Blues,News Of The World,MPEG audio file

In [236]:
#q19
query = """
SELECT Track.TrackId, Track.Name AS TrackName, Genre.Name AS GenreName
FROM Track
JOIN Genre ON Track.GenreId = Genre.GenreId
JOIN Album ON Track.AlbumId = Album.AlbumId
JOIN Artist ON Album.ArtistId = Artist.ArtistId
WHERE Artist.Name = 'Queen'
ORDER BY Track.TrackId;
"""
q19_df = pd.read_sql(query, engine)
q19_df.to_pickle("q19.pkl")
q19_df

    TrackId                       TrackName GenreName
0       419                 A Kind Of Magic      Rock
1       420                  Under Pressure      Rock
2       421                     Radio GA GA      Rock
3       422                   I Want It All      Rock
4       423            I Want To Break Free      Rock
5       424                        Innuendo      Rock
6       425                It's A Hard Life      Rock
7       426                       Breakthru      Rock
8       427       Who Wants To Live Forever      Rock
9       428                        Headlong      Rock
10      429                     The Miracle      Rock
11      430          I'm Going Slightly Mad      Rock
12      431               The Invisible Man      Rock
13      432                  Hammer To Fall      Rock
14      433         Friends Will Be Friends      Rock
15      434             The Show Must Go On      Rock
16      435                      One Vision      Rock
17     2254               Bohemian Rhapsody      Rock
18     2255      Another One Bites The Dust      Rock
19     2256                    Killer Queen      Rock
20     2257              Fat Bottomed Girls      Rock
21     2258                    Bicycle Race      Rock
22     2259           You're My Best Friend      Rock
23     2260               Don't Stop Me Now      Rock
24     2261                         Save Me      Rock
25     2262  Crazy Little Thing Called Love      Rock
26     2263                Somebody To Love      Rock
27     2264                    Now I'm Here      Rock
28     2265    Good Old-Fashioned Lover Boy      Rock
29     2266                   Play The Game      Rock
30     2267                           Flash      Rock
31     2268              Seven Seas Of Rhye      Rock
32     2269                We Will Rock You      Rock
33     2270            We Are The Champions      Rock
34     2271                We Will Rock You      Rock
35     2272            We Are The Champions      Rock
36     2273              Sheer Heart Attack      Rock
37     2274              All Dead, All Dead      Rock
38     2275               Spread Your Wings      Rock
39     2276           Fight From The Inside      Rock
40     2277             Get Down, Make Love      Rock
41     2278           Sleep On The Sidewalk      Rock
42     2279                   Who Needs You      Rock
43     2280                       It's Late      Rock
44     2281             My Melancholy Blues      Rock

In [237]:
#q20
query = """
SELECT DISTINCT Invoice.InvoiceId, Invoice.InvoiceDate, Invoice.BillingCity, Invoice.BillingState, Invoice.CustomerId
FROM Invoice
JOIN Customer ON Invoice.CustomerId = Customer.CustomerId
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
WHERE Customer.Country = 'USA'
AND InvoiceLine.TrackId IN (
    SELECT Track.TrackId
    FROM Track
    JOIN Album ON Track.AlbumId = Album.AlbumId
    JOIN Artist ON Album.ArtistId = Artist.ArtistId
    WHERE Artist.Name = 'Queen'
)
ORDER BY Invoice.InvoiceId;
"""
q20_df = pd.read_sql(query, engine)
q20_df.to_pickle("q20.pkl")
q20_df

   InvoiceId InvoiceDate BillingCity BillingState  CustomerId
0        332  2024-12-30     Chicago           IL          24
1        386  2025-09-02      Tucson           AZ          27

In [238]:
#q21
query = """
SELECT DISTINCT Playlist.Name AS PlaylistName
FROM Playlist
JOIN PlaylistTrack ON Playlist.PlaylistId = PlaylistTrack.PlaylistId
JOIN Track ON PlaylistTrack.TrackId = Track.TrackId
JOIN Album ON Track.AlbumId = Album.AlbumId
JOIN Artist ON Album.ArtistId = Artist.ArtistId
WHERE Artist.Name = 'Queen'
ORDER BY Playlist.Name;
"""
q21_df = pd.read_sql(query, engine)
q21_df.to_pickle("q21.pkl")
q21_df

  PlaylistName
0   90’s Music
1        Music

In [239]:
#q22
query = """
SELECT DISTINCT Employee.EmployeeId, Employee.FirstName, Employee.LastName
FROM Employee
JOIN Customer ON Employee.EmployeeId = Customer.SupportRepId
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
WHERE InvoiceLine.TrackId IN (
    SELECT Track.TrackId
    FROM Track
    JOIN Album ON Track.AlbumId = Album.AlbumId
    JOIN Artist ON Album.ArtistId = Artist.ArtistId
    WHERE Artist.Name = 'Queen'
)
ORDER BY Employee.EmployeeId;
"""
q22_df = pd.read_sql(query, engine)
q22_df.to_pickle("q22.pkl")
q22_df

   EmployeeId FirstName LastName
0           3      Jane  Peacock
1           4  Margaret     Park
2           5     Steve  Johnson

In [240]:
#q23
conn.execute(text("""
    ALTER TABLE Album MODIFY Title VARCHAR(255) COLLATE utf8mb4_general_ci;
"""))

conn.execute(text("""
    SET collation_connection = 'utf8mb4_general_ci';
"""))

query = """
SELECT Album.Title AS AlbumTitle, Artist.Name AS ArtistName
FROM Album
LEFT JOIN Artist ON Album.ArtistId = Artist.ArtistId
ORDER BY Album.Title, Artist.Name;
"""
q23_df = pd.read_sql(query, engine)
q23_df.to_pickle("q23.pkl")
q23_df

,AlbumTitle,ArtistName
0,...And Justice For All,Metallica
1,20th Century Masters - The Millennium Collecti...,Scorpions
2,"A Copland Celebration, Vol. I",Aaron Copland & London Symphony Orchestra
3,A Matter of Life and Death,Iron Maiden
4,A Real Dead One,Iron Maiden
...,...,...
342,Warner 25 Anos,Antônio Carlos Jobim
343,Weill: The Seven Deadly Sins,Kent Nagano and Orchestre de l'Opéra de Lyon
344,Worlds,Aaron Goldberg
345,Zooropa,U2
346,[1997] Black Light Syndrome,"Terry Bozzio, Tony Levin & Steve Stevens"

In [241]:
#q24
query = """
SELECT COALESCE(Artist.Name, 'Unknown Artist') AS ArtistName, 
       Album.Title AS AlbumTitle
FROM Album
RIGHT JOIN Artist ON Album.ArtistId = Artist.ArtistId
ORDER BY ArtistName ASC, AlbumTitle ASC;
"""
q24_df = pd.read_sql(query, engine)
q24_df.to_pickle("q24.pkl")
q24_df

,ArtistName,AlbumTitle
0,A Cor Do Som,None
1,Aaron Copland & London Symphony Orchestra,"A Copland Celebration, Vol. I"
2,Aaron Goldberg,Worlds
3,AC/DC,For Those About To Rock We Salute You
4,AC/DC,Let There Be Rock
...,...,...
413,Xis,None
414,Yehudi Menuhin,Bartok: Violin & Viola Concertos
415,Yo-Yo Ma,Bach: The Cello Suites
416,Youssou N'Dour,None
417,Zeca Pagodinho,Ao Vivo [IMPORT]

In [242]:
#q25
query = """
SELECT GenreId, COUNT(*) AS TrackCount
FROM Track
GROUP BY GenreId
ORDER BY TrackCount DESC, GenreId ASC;
"""
q25_df = pd.read_sql(query, engine)
q25_df.to_pickle("q25.pkl")
q25_df

    GenreId  TrackCount
0         1        1297
1         7         579
2         3         374
3         4         332
4         2         130
5        19          93
6         6          81
7        24          74
8        21          64
9        14          61
10        8          58
11        9          48
12       10          43
13       23          40
14       17          35
15       15          30
16       13          28
17       16          28
18       20          26
19       12          24
20       22          17
21       11          15
22       18          13
23        5          12
24       25           1

In [255]:
#q26
query = """
SELECT Album.AlbumId, Album.Title AS AlbumTitle, 
       ROUND(SUM(Track.Milliseconds) / 3600000, 4) AS TotalDurationHours  -- Increased precision to 4 decimal places
FROM Album
JOIN Track ON Album.AlbumId = Track.AlbumId
GROUP BY Album.AlbumId, Album.Title
ORDER BY TotalDurationHours DESC
LIMIT 5;
"""
q26_df = pd.read_sql(query, engine)
q26_df.to_pickle("q26.pkl")
q26_df

   AlbumId                                AlbumTitle  TotalDurationHours
0      229                            Lost, Season 3             19.6293
1      253  Battlestar Galactica (Classic), Season 1             19.5038
2      230                            Lost, Season 1             18.0153
3      231                            Lost, Season 2             17.5805
4      228                          Heroes, Season 1             16.6056

In [256]:
#q27
query = """
SELECT Album.Title AS AlbumTitle, 
       COUNT(DISTINCT Track.GenreId) AS GenreCount
FROM Album
JOIN Track ON Album.AlbumId = Track.AlbumId
GROUP BY Album.AlbumId, Album.Title
HAVING COUNT(DISTINCT Track.GenreId) > 1
ORDER BY GenreCount DESC, AlbumTitle ASC;
"""
q27_df = pd.read_sql(query, engine)
q27_df.to_pickle("q27.pkl")
q27_df

                        AlbumTitle  GenreCount
0   Battlestar Galactica, Season 3           3
1                    Greatest Hits           3
2                 Heroes, Season 1           2
3                 Live After Death           2
4                   Lost, Season 2           2
5                   Lost, Season 3           2
6                   LOST, Season 4           2
7                Rock In Rio [CD2]           2
8          The Number of The Beast           2
9             The Office, Season 3           2
10                       Unplugged           2

In [257]:
#q28
query = """
SELECT Artist.Name AS ArtistName, 
       ROUND(SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity), 2) AS TotalRevenue
FROM Artist
JOIN Album ON Artist.ArtistId = Album.ArtistId
JOIN Track ON Album.AlbumId = Track.AlbumId
JOIN InvoiceLine ON Track.TrackId = InvoiceLine.TrackId
GROUP BY Artist.ArtistId, Artist.Name
ORDER BY TotalRevenue DESC, ArtistName ASC;
"""
q28_df = pd.read_sql(query, engine)
q28_df.to_pickle("q28.pkl")
q28_df

                                     ArtistName  TotalRevenue
0                                   Iron Maiden        138.60
1                                            U2        105.93
2                                     Metallica         90.09
3                                  Led Zeppelin         86.13
4                                          Lost         81.59
..                                          ...           ...
160  The 12 Cellists of The Berlin Philharmonic          0.99
161                          The King's Singers          0.99
162                                  The Posies          0.99
163                              Yehudi Menuhin          0.99
164                                    Yo-Yo Ma          0.99

[165 rows x 2 columns]

In [258]:
#q29
query = """
SELECT Genre.Name AS GenreName, 
       ROUND(AVG(Track.Milliseconds) / 60000, 4) AS AverageDurationMinutes  -- Increased precision to 4 decimal places
FROM Genre
JOIN Track ON Genre.GenreId = Track.GenreId
GROUP BY Genre.GenreId, Genre.Name
HAVING AVG(Track.Milliseconds) / 60000 > 20
ORDER BY AverageDurationMinutes DESC;
"""
q29_df = pd.read_sql(query, engine)
q29_df.to_pickle("q29.pkl")
q29_df

          GenreName  AverageDurationMinutes
0  Sci Fi & Fantasy                 48.5297
1   Science Fiction                 43.7592
2             Drama                 42.9214
3          TV Shows                 35.7507
4            Comedy                 26.4211

In [308]:
#q30
query = """
SELECT Customer.CustomerId, Customer.FirstName, Customer.LastName, 
       SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalExpenditure,
       RANK() OVER (ORDER BY SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) DESC) AS ExpenditureRank
FROM Customer
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
JOIN Track ON InvoiceLine.TrackId = Track.TrackId
WHERE Track.AlbumId IN (
    SELECT AlbumId FROM Album WHERE ArtistId = (
        SELECT ArtistId FROM Artist WHERE Name = 'Queen'
    )
)
GROUP BY Customer.CustomerId, Customer.FirstName, Customer.LastName
ORDER BY TotalExpenditure DESC, Customer.CustomerId ASC
"""
q30_df = pd.read_sql(query, engine)
q30_df.to_pickle("q30.pkl")
q30_df

    CustomerId  FirstName    LastName  TotalExpenditure  ExpenditureRank
0           24      Frank     Ralston              3.96                1
1           29     Robert       Brown              3.96                1
2           33      Ellie    Sullivan              3.96                1
3           40  Dominique    Lefebvre              3.96                1
4           50    Enrique       Muñoz              3.96                1
5           11  Alexandre       Rocha              2.97                6
6            2     Leonie      Köhler              1.98                7
7           38     Niklas    Schröder              1.98                7
8           44      Terhi  Hämäläinen              1.98                7
9           45   Ladislav      Kovács              1.98                7
10          47      Lucas     Mancini              1.98                7
11          27    Patrick        Gray              0.99               12
12          30     Edward     Francis              0.99               12
13          41       Marc      Dubois              0.99               12
14          49  Stanisław      Wójcik              0.99               12

In [323]:
#q31
query = """
SELECT Track.TrackId, 
       Track.Name AS TrackName, 
       ROUND(Track.Milliseconds / 60000, 4) AS DurationMinutes,
       RANK() OVER (ORDER BY Track.Milliseconds DESC) AS DurationRank
FROM Track
ORDER BY DurationRank ASC, TrackId ASC;
"""
q31_df = pd.read_sql(query, engine)
q31_df.to_pickle("q31.pkl")
q31_df

      TrackId                    TrackName  DurationMinutes  DurationRank
0        2820       Occupation / Precipice          88.1159             1
1        3224      Through a Looking Glass          84.8140             2
2        3244  Greetings from Earth, Pt. 1          49.3382             3
3        3242      The Man With Nine Lives          49.2833             4
4        3227  Battlestar Galactica, Pt. 2          49.2680             5
...       ...                          ...              ...           ...
3498     3304                 Commercial 1           0.1324          3499
3499      178                        Oprah           0.1106          3500
3500      170                  A Statistic           0.1062          3501
3501      168                   Now Sports           0.0814          3502
3502     2461     É Uma Partida De Futebol           0.0179          3503

[3503 rows x 4 columns]

In [338]:
#q32
query = """
SELECT Customer.CustomerId, Customer.FirstName, Customer.LastName, 
       SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) AS TotalExpenditure,
       RANK() OVER (ORDER BY SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) DESC) AS ExpenditureRank
FROM Customer
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
JOIN InvoiceLine ON Invoice.InvoiceId = InvoiceLine.InvoiceId
JOIN Track ON InvoiceLine.TrackId = Track.TrackId
WHERE Track.AlbumId IN (
    SELECT AlbumId FROM Album WHERE ArtistId = (
        SELECT ArtistId FROM Artist WHERE Name = 'Queen'
    )
)
GROUP BY Customer.CustomerId, Customer.FirstName, Customer.LastName
ORDER BY TotalExpenditure DESC, Customer.CustomerId ASC;
"""
q32_df = pd.read_sql(query, engine)
q32_df.to_pickle("q32.pkl")
q32_df

    CustomerId  FirstName    LastName  TotalExpenditure  ExpenditureRank
0           24      Frank     Ralston              3.96                1
1           29     Robert       Brown              3.96                1
2           33      Ellie    Sullivan              3.96                1
3           40  Dominique    Lefebvre              3.96                1
4           50    Enrique       Muñoz              3.96                1
5           11  Alexandre       Rocha              2.97                6
6            2     Leonie      Köhler              1.98                7
7           38     Niklas    Schröder              1.98                7
8           44      Terhi  Hämäläinen              1.98                7
9           45   Ladislav      Kovács              1.98                7
10          47      Lucas     Mancini              1.98                7
11          27    Patrick        Gray              0.99               12
12          30     Edward     Francis              0.99               12
13          41       Marc      Dubois              0.99               12
14          49  Stanisław      Wójcik              0.99               12

In [339]:
#q33
query = """
SELECT Customer.CustomerId, Customer.FirstName, Customer.LastName, 
       COUNT(Invoice.InvoiceId) AS InvoicesCount,
       DENSE_RANK() OVER (ORDER BY COUNT(Invoice.InvoiceId) DESC, Customer.LastName ASC) AS InvoiceRank
FROM Customer
JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId
GROUP BY Customer.CustomerId, Customer.FirstName, Customer.LastName
ORDER BY InvoiceRank ASC;
"""
q33_df = pd.read_sql(query, engine)
q33_df.to_pickle("q33.pkl")
q33_df

    CustomerId  FirstName      LastName  InvoicesCount  InvoiceRank
0           12    Roberto       Almeida              7            1
1           28      Julia       Barnett              7            2
2           39    Camille       Bernard              7            3
3           18   Michelle        Brooks              7            4
4           29     Robert         Brown              7            5
5           21      Kathy         Chase              7            6
6           26    Richard    Cunningham              7            7
7           41       Marc        Dubois              7            8
8           34       João     Fernandes              7            9
9           30     Edward       Francis              7           10
10          42      Wyatt        Girard              7           11
11           1       Luís     Gonçalves              7           12
12          23       John        Gordon              7           13
13          19        Tim         Goyer              7           14
14          27    Patrick          Gray              7           15
15           7     Astrid        Gruber              7           16
16          56      Diego     Gutiérrez              7           17
17          44      Terhi    Hämäläinen              7           18
18           4      Bjørn        Hansen              7           19
19          16      Frank        Harris              7           20
20           6     Helena          Holý              7           21
21          53       Phil        Hughes              7           22
22          51     Joakim     Johansson              7           23
23          52       Emma         Jones              7           24
24           2     Leonie        Köhler              7           25
25          45   Ladislav        Kovács              7           26
26          22    Heather       Leacock              7           27
27          40  Dominique      Lefebvre              7           28
28          47      Lucas       Mancini              7           29
29          10    Eduardo       Martins              7           30
30          43   Isabelle       Mercier              7           31
31          20        Dan        Miller              7           32
32          32      Aaron      Mitchell              7           33
33          50    Enrique         Muñoz              7           34
34          54      Steve        Murray              7           35
35           9       Kara       Nielsen              7           36
36          46       Hugh      O'Reilly              7           37
37          58      Manoj        Pareek              7           38
38           8       Daan       Peeters              7           39
39          15   Jennifer      Peterson              7           40
40          14       Mark       Philips              7           41
41          24      Frank       Ralston              7           42
42          13   Fernanda         Ramos              7           43
43          11  Alexandre         Rocha              7           44
44          57       Luis         Rojas              7           45
45          35   Madalena       Sampaio              7           46
46          36     Hannah     Schneider              7           47
47          38     Niklas      Schröder              7           48
48          31     Martha          Silk              7           49
49          17       Jack         Smith              7           50
50          25     Victor       Stevens              7           51
51          33      Ellie      Sullivan              7           52
52          55       Mark        Taylor              7           53
53           3   François      Tremblay              7           54
54          48   Johannes  Van der Berg              7           55
55           5  František   Wichterlová              7           56
56          49  Stanisław        Wójcik              7           57
57          37       Fynn    Zimmermann              7           58
58          59       Puja    Srivastava              6           59

In [340]:
#q34
query = """
WITH InvoiceRanking AS (
    SELECT Invoice.BillingCountry, Invoice.InvoiceId, Invoice.Total,
           RANK() OVER (PARTITION BY Invoice.BillingCountry ORDER BY Invoice.Total DESC) AS InvoiceRank
    FROM Invoice
)
SELECT BillingCountry, InvoiceId, Total, InvoiceRank
FROM InvoiceRanking
WHERE InvoiceRank <= 3
ORDER BY BillingCountry ASC, Total DESC, InvoiceId ASC;
"""
q34_df = pd.read_sql(query, engine)
q34_df.to_pickle("q34.pkl")
q34_df

    BillingCountry  InvoiceId  Total  InvoiceRank
0        Argentina        348  13.86            1
1        Argentina        403   8.91            2
2        Argentina        164   5.94            3
3        Australia        250  13.86            1
4        Australia        305   8.91            2
..             ...        ...    ...          ...
80  United Kingdom        152  13.86            1
81  United Kingdom        369  13.86            1
82             USA        299  23.86            1
83             USA        201  18.86            2
84             USA        103  15.86            3

[85 rows x 4 columns]

In [344]:
#q35
query = """
WITH MonthlySales AS (
    SELECT DATE_FORMAT(Invoice.InvoiceDate, '%Y-%m') AS Month,
           SUM(Invoice.Total) AS MonthlySales
    FROM Invoice
    GROUP BY DATE_FORMAT(Invoice.InvoiceDate, '%Y-%m')
)
SELECT Month, 
       ROUND(MonthlySales, 2) AS MonthlySales,  -- Keep MonthlySales at 2 decimals
       ROUND(AVG(MonthlySales) OVER (ORDER BY Month ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 6) AS MovingAverageSales
FROM MonthlySales
ORDER BY Month ASC;
"""
q35_df = pd.read_sql(query, engine)
q35_df.to_pickle("q35.pkl")
q35_df

      Month  MonthlySales  MovingAverageSales
0   2021-01         35.64           35.640000
1   2021-02         37.62           36.630000
2   2021-03         37.62           36.960000
3   2021-04         37.62           37.620000
4   2021-05         37.62           37.620000
5   2021-06         37.62           37.620000
6   2021-07         37.62           37.620000
7   2021-08         37.62           37.620000
8   2021-09         37.62           37.620000
9   2021-10         37.62           37.620000
10  2021-11         37.62           37.620000
11  2021-12         37.62           37.620000
12  2022-01         52.62           42.620000
13  2022-02         46.62           45.620000
14  2022-03         44.62           47.953333
15  2022-04         37.62           42.953333
16  2022-05         37.62           39.953333
17  2022-06         37.62           37.620000
18  2022-07         37.62           37.620000
19  2022-08         37.62           37.620000
20  2022-09         36.63           37.290000
21  2022-10         37.62           37.290000
22  2022-11         37.62           37.290000
23  2022-12         37.62           37.620000
24  2023-01         37.62           37.620000
25  2023-02         37.62           37.620000
26  2023-03         37.62           37.620000
27  2023-04         51.62           42.286667
28  2023-05         42.62           43.953333
29  2023-06         50.62           48.286667
30  2023-07         37.62           43.620000
31  2023-08         37.62           41.953333
32  2023-09         37.62           37.620000
33  2023-10         37.62           37.620000
34  2023-11         23.76           33.000000
35  2023-12         37.62           33.000000
36  2024-01         37.62           33.000000
37  2024-02         37.62           37.620000
38  2024-03         37.62           37.620000
39  2024-04         37.62           37.620000
40  2024-05         37.62           37.620000
41  2024-06         37.62           37.620000
42  2024-07         39.62           38.286667
43  2024-08         47.62           41.620000
44  2024-09         46.71           44.650000
45  2024-10         42.62           45.650000
46  2024-11         37.62           42.316667
47  2024-12         37.62           39.286667
48  2025-01         37.62           37.620000
49  2025-02         27.72           34.320000
50  2025-03         37.62           34.320000
51  2025-04         33.66           33.000000
52  2025-05         37.62           36.300000
53  2025-06         37.62           36.300000
54  2025-07         37.62           37.620000
55  2025-08         37.62           37.620000
56  2025-09         37.62           37.620000
57  2025-10         37.62           37.620000
58  2025-11         49.62           41.620000
59  2025-12         38.62           41.953333

In [345]:
!python3 autograder.py

Archive:  answers.zip
  inflating: answers/answers/pkls/p24.pkl
  inflating: answers/answers/pkls/p31.pkl
  inflating: answers/answers/pkls/p5.pkl
  inflating: answers/answers/pkls/p2.pkl
  inflating: answers/answers/pkls/p29.pkl
  inflating: answers/answers/pkls/p4.pkl
  inflating: answers/answers/pkls/p30.pkl
  inflating: answers/answers/pkls/p8.pkl
  inflating: answers/answers/pkls/p3.pkl
  inflating: answers/answers/pkls/p6.pkl
  inflating: answers/answers/pkls/p22.pkl
  inflating: answers/answers/pkls/p23-s2.pkl
  inflating: answers/answers/pkls/p13.pkl
  inflating: answers/answers/pkls/p23.pkl
  inflating: answers/answers/pkls/p9.pkl
  inflating: answers/answers/pkls/p34.pkl
  inflating: answers/answers/pkls/p20.pkl
  inflating: answers/answers/pkls/p12.pkl
  inflating: answers/answers/pkls/p1.pkl
  inflating: answers/answers/pkls/p32.pkl
  inflating: answers/answers/pkls/p33.pkl
  inflating: answers/answers/pkls/p27.pkl
  inflating: answers/answers/pkls/p7.pkl
  inflating: answers/answers/pkls/p11.pkl
  inflating: answers/answers/pkls/p18.pkl
  inflating: answers/answers/pkls/p26.pkl
  inflating: answers/answers/pkls/p25.pkl
  inflating: answers/answers/pkls/p15.pkl
  inflating: answers/answers/pkls/p14.pkl
  inflating: answers/answers/pkls/p35.pkl
  inflating: answers/answers/pkls/p21.pkl
  inflating: answers/answers/pkls/p28.pkl
  inflating: answers/answers/pkls/p17.pkl
  inflating: answers/answers/pkls/p10.pkl
  inflating: answers/answers/pkls/p19.pkl
  inflating: answers/answers/pkls/p16.pkl
Processed q1
Processed q2
Processed q3
Processed q4
Processed q5
Processed q6
Processed q7
Processed q8
Processed q9
Processed q10
Processed q11
Processed q12
Processed q13
Processed q14
Processed q15
Processed q16
Processed q17
Processed q18
Processed q19
Processed q20
Processed q21
Processed q22
Processed q23
Processed q24
Processed q25
Processed q26
Processed q27
Processed q28
Processed q29
Processed q30
Processed q31
Processed q32
Processed q33
Processed q34
Processed q35
-----------------------------
Total Score: 90.0/90.0
-----------------------------
Run `cat test_output.txt` for individual question-wise results :)

In [346]:
!cat test_output.txt

Connection to database established: 2.5 points
Question 1: 2.5/2.5 points
Question 2: 2.5/2.5 points
Question 3: 2.5/2.5 points
Question 4: 2.5/2.5 points
Question 5: 2.5/2.5 points
Question 6: 2.5/2.5 points
Question 7: 2.5/2.5 points
Question 8: 2.5/2.5 points
Question 9: 2.5/2.5 points
Question 10: 2.5/2.5 points
Question 11: 2.5/2.5 points
Question 12: 2.5/2.5 points
Question 13: 2.5/2.5 points
Question 14: 2.5/2.5 points
Question 15: 2.5/2.5 points
Question 16: 2.5/2.5 points
Question 17: 2.5/2.5 points
Question 18: 2.5/2.5 points
Question 19: 2.5/2.5 points
Question 20: 2.5/2.5 points
Question 21: 2.5/2.5 points
Question 22: 2.5/2.5 points
Question 23: 2.5/2.5 points
Question 24: 2.5/2.5 points
Question 25: 2.5/2.5 points
Question 26: 2.5/2.5 points
Question 27: 2.5/2.5 points
Question 28: 2.5/2.5 points
Question 29: 2.5/2.5 points
Question 30: 2.5/2.5 points
Question 31: 2.5/2.5 points
Question 32: 2.5/2.5 points
Question 33: 2.5/2.5 points
Question 34: 2.5/2.5 points
Question 35: 2.5/2.5 points
---------------------------------------------------------------
 Total Score: 90.0/90.0
---------------------------------------------------------------